CC	= kos-cc
CXX	= kos-c++

CFLAGS		+= -DLSB_FIRST -DALIGN_DWORD -DDREAMCAST -DNOMUTEX -Ofast
CFLAGS		+= -Isrc
CXXFLAGS =  $(CFLAGS) -std=gnu17 -fno-exceptions -fno-rtti

#LDFLAGS = -lSDL -ltremor -lm -lz

#Including OPUS Libraries
LDFLAGS = -lc -lm -lSDL -lz -s -flto -Wl,--as-needed -Wl,--gc-sections
OUTPUT = llama_dc.elf

SRCDIR		=  ./src
VPATH		= $(SRCDIR)
SRC_C		= $(foreach dir, $(SRCDIR), $(wildcard $(dir)/*.c))
SRC_CP		= $(foreach dir, $(SRCDIR), $(wildcard $(dir)/*.cpp))
OBJ_C		= $(notdir $(patsubst %.c, %.o, $(SRC_C)))
OBJ_CP		= $(notdir $(patsubst %.cpp, %.o, $(SRC_CP)))
OBJS		= $(OBJ_C) $(OBJ_CP)

all: ${OUTPUT}

${OUTPUT}: ${OBJS}
	${CXX} ${CXXFLAGS} -o ${OUTPUT} ${OBJS} ${LDFLAGS} 

pack_unused_cdda:
	rm -f IP.BIN
	sh-elf-objcopy -R .stack -O binary $(OUTPUT) main.bin
	${KOS_BASE}/utils/scramble/scramble main.bin ./cd/1ST_READ.BIN
	makeip ip.txt IP.BIN
	mkisofs -C 0,$(shell lbacalc track1.raw track2.raw track3.raw) -V OVERHEATED -G IP.BIN -joliet -rock -l -o "llama.iso" ./cd
	mds4dc -c llama.mds llama.iso track1.raw track2.raw track3.raw
	
pack:
	rm -f IP.BIN
	sh-elf-objcopy -R .stack -O binary $(OUTPUT) main.bin
	${KOS_BASE}/utils/scramble/scramble main.bin ./cd/1ST_READ.BIN
	makeip ip.txt IP.BIN
	mkisofs -V llama -G IP.BIN -joliet -rock -l -x cd -o "llama.iso" ./cd
	cdi4dc llama.iso llama.cdi -d
	
clean:
	rm *.o *.img src/*.o src/sdl/*.o src/dc/*.o src/enemies/*.o ${OUTPUT} *.BIN *.iso *.mds *.mdf
